server:
  port: 8080

spring:
  profiles:
    active: native # dev
  application:
    name: burst-config #@pom.artifactId@
  #rabbitmq:
    #host: burst-mq-rabbit
    #port: 5672
    #username: guest
    #password: guest
  boot:
    admin:
      username: admin
      password: admin

security:
  user:
    name: admin
    password: admin