server:
  port: 7979

spring:
  profiles:
    active: dev
  application:
    name: burst-gateway # @pom.artifactId@

swagger:
  title: burst-gateway  # @pom.artifactId@
  description: Demo project for Spring Boot # @pom.description@