spring:
  boot:
    admin:
      client:
        metadata-map:
          username: ${security.user.name}
          password: ${security.user.password}
      monitor:
        period: 60000
      discovery:
        enabled: true
      turbine:
        clusters: default
        location: durst-monitor
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

security:
  user:
    name: admin
    password: admin
  basic:
    enabled: false

turbine:
  app-config: burst-gateway #收集监控信息的服务名
  combine-host-port: true
  cluster-name-expression: new String('default') #集群名称